name: Deploy AWS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x
        
    - name: List files in the repository
      run: |
        ls -a      
      
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish
      run: dotnet publish -c Release -o '${{ github.workspace }}/backend/out'
    - name: Zip Package
      run: |
        cd ${{ github.workspace }}/backend/out 
        zip -r ${{ github.workspace }}/backend/out.zip *
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v13
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: esesmt
        environment_name: Esesmt-env
        region: us-east-2
        version_label: ${{ github.run_id }}
        version_description: ${{ github.sha }}
        deployment_package: ${{ github.workspace }}/backend/out.zip
